### ISSUE TITLE
Remove source code from menu, replace with clubs

### ISSUE THREAD

**Issue by jeanbza** [jadekler/git-reactjs-pongboard#10]
Usecases:
- When a user hits http://app.com, it should take them to a list of clubs with no menu bar.
- When a user hits http://app.com/feed / leaderboard / etc, it should take them to feed / leaderboard / etc with a menu bar containing Clubs, Feed, Leaderboard, About.

**Comment by elainemckinley** [comment]
Finished as of efee65568da6a1256957feea11458c80447b7b88
